### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by ALLENGJOSE**
Fixed issue #4 .I implemented Using one push with 2 objects instead.

### CODE REVIEW

**Comment by ravut8** [comment]
Hey @ALLENGJOSE, thanks for the PR on issue 4. Just one minor adjustment. Could you create a new branch (refactor/4-update-push-element-in-test-case) and push the "Refactored code" to the new branch? Then, submit another pull request. Currently, there are two commits from two separate PRs.

If you are ok with this, I will go ahead and close this PR. Thanks again 🙏

**Comment by ALLENGJOSE** [comment]
how do I push "Refactored code" to the new branch? Sorry , but I am new to open source. I would be grateful if you could tell me how to do it?

**Comment by ravut8** [comment]
No worries @ALLENGJOSE , here are the summarized steps:
1. Create a new branch - refactor/4-update-push-element-in-test-case
2. Make changes to the new branch
3. Commit your changes

Note: Unfortunately, for commit [3cf3cc7](https://github.com/logicspark/berryjam/pull/27/commits/3cf3cc7db6469c3da8005d9417381e815c2abd51), you will need to redo and commit to the new branch.

**Comment by ravut8** [comment]
Hey @ALLENGJOSE, almost there!

I notice that there are many commits in PR #30. Unfortunately, I cannot accept the PR because it will merge all commits into the Berryjam's main. To solve this issue, you could either delete this branch and create another branch OR just create another branch and select `main` as source. After that, redo the refactored code.

Select Main Source

Note: If you wish to create another branch you can use "refactor/4-update-push-element-in-test"

P.S. Please apply this concept to the rest of your PRs 🙏

**Comment by ALLENGJOSE** [comment]
Thank you for the cooperation.  What I am doing is deleting all branches and redoing this all over again. Please bear with me . I want to get this done

**Pull request closed without merging**
